apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitSend
  labels:
    app: kitSend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kitSend
  template:
    metadata:
      labels:
        app: kitSend
    spec:
      containers:
        - name: kitSend
          image: username/kitSend:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5